(env
 (_
  (flags
   (:standard -w -9-32-39))))

(library
 (name Tast_pattern)
 (modules Tast_pattern MyPrinttyped MyUntype)
 (wrapped false)
 (libraries ppxlib)
 (preprocess
  (pps
   ppx_optcomp
   ppx_inline_test
   --
   ; -pp "cppo -V OCAML:4.02.1"
   -pp
   "cppo -V OCAML:4.12.1"))
 (inline_tests))
